# Create docker compose config for mysql db.
version: '3.3'
networks:
  default:

services:
  db:
    image: mysql:5.7
    container_name: catalogdb
    ports:
      - "3306:3306"
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalogdb
      MYSQL_USER: catalog
      MYSQL_PASSWORD: catalog