@startuml

    title "Controller testing estrategy"

    class ControllerTest {
        - mockMvc: MockMvc
        - mockService: Service

    }

    class Service {
        - repository: Repository
    }

    class MockMvc {
        + perform()
        + andExpect()
        + andReturn()
    }

    ControllerTest --> Service
    ControllerTest --> MockMvc



@enduml